const CLAUSES = {
  NON_MEDICAL: 'Clause 4.2(a) - Non-Medical Items',
  ROOM_RENT: 'Clause 3.1 - Room Rent Cap',
  PROCEDURE_SUBLIMIT: 'Clause 5.1 - Procedure Sub-limit',
  WAITING_PERIOD: 'Clause 6.1 - Pre-existing Waiting Period',
  SUM_INSURED_EXHAUSTED: 'Clause 1.1 - Sum Insured Exhausted',
  IOL_TARIFF_CAP: 'Clause 2.3 - IOL Tariff Cap'
};

const REASON_CODES = {
  NON_PAYABLE_CONSUMABLE: 'NON_PAYABLE_CONSUMABLE',
  SUB_LIMIT_EXCEEDED: 'SUB_LIMIT_EXCEEDED',
  WAITING_PERIOD_ACTIVE: 'WAITING_PERIOD_ACTIVE',
  SI_EXCEEDED: 'SI_EXCEEDED',
  TARIFF_CAP_EXCEEDED: 'TARIFF_CAP_EXCEEDED',
  FRAUD_WAITING_PERIOD: 'FRAUD_WAITING_PERIOD',
  FRAUD_DUPLICATE_EYE: 'FRAUD_DUPLICATE_EYE',
  FRAUD_TARIFF_BREACH: 'FRAUD_TARIFF_BREACH',
  FRAUD_RAPID_SECOND_EYE: 'FRAUD_RAPID_SECOND_EYE',
  MISSING_DOCUMENT: 'MISSING_DOCUMENT'
};

const NON_PAYABLE_ITEMS = [
  'GLOVES', 'ADMIN_FEE', 'STATIONERY', 'REGISTRATION_FEE', 'DIET_CHARGES'
];

module.exports = {
  CLAUSES,
  REASON_CODES,
  NON_PAYABLE_ITEMS
};
